version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - '5432:5432'

  app:
    build: .
    environment:
      DATABASE_URL: 'postgresql://user:password@database:5432/database?schema=public'
    depends_on:
      - database
    ports:
      - '3000:3000'
