name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: intall nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.5

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: intall nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.5

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: test
        run: pnpm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t nodejs-fly.io .

  deploy-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.5

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Apply all pending migrations to the database
        run: pnpm deploy:db
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
