name: CI
run-name: ${{ github.actor }} is integrating on GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubunto-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t nodejs-fly.io
